
#define TAUT_ROPE_DISTANCE_TOLERANCE			(0.01f)
#define TAUT_ROPE_DISTANCE_TOLERANCE_SQUARED	(TAUT_ROPE_DISTANCE_TOLERANCE * TAUT_ROPE_DISTANCE_TOLERANCE)
#define TAUT_ROPE_MAX_MOVEMENT_ITERATIONS		(10)
#define TAUT_ROPE_MAX_COLLISION_ITERATIONS		(10)
#define TAUT_ROPE_DEBUG_DRAWING					!(UE_BUILD_SHIPPING || UE_BUILD_TEST)