#define TAUT_ROPE_DEBUG_DRAWING							!(UE_BUILD_SHIPPING || UE_BUILD_TEST)

#define TAUT_ROPE_DISTANCE_TOLERANCE					(0.01f)
#define TAUT_ROPE_VERTEX_CROSSING_OFFSET				(0.1f)
#define TAUT_ROPE_SHAPE_MERGE_VERTEX_THRESHOLD			(0.1f)
#define TAUT_ROPE_SHAPE_EDGE_RAY_INCREMENT_DISTANCE		(1.f)

#define TAUT_ROPE_MAX_COLLISION_ITERATIONS				(100)

#define TAUT_ROPE_DISTANCE_TOLERANCE_SQUARED			(TAUT_ROPE_DISTANCE_TOLERANCE * TAUT_ROPE_DISTANCE_TOLERANCE)
#define TAUT_ROPE_SHAPE_MERGE_VERTEX_THRESHOLD_SQUARED	(TAUT_ROPE_SHAPE_MERGE_VERTEX_THRESHOLD * TAUT_ROPE_SHAPE_MERGE_VERTEX_THRESHOLD)
#define TAUT_ROPE_SHAPE_EDGE_RAY_INCREMENT_DISTANCE_SQUARED		(TAUT_ROPE_SHAPE_EDGE_RAY_INCREMENT_DISTANCE * TAUT_ROPE_SHAPE_EDGE_RAY_INCREMENT_DISTANCE)